spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3310/blog1
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      data-source:

#    schema:
#      - classpath:schema-article.sql
#    data:
#      - classpath:data-bb.sql