spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3310/blog1
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    # 密码 没有则可以不填
    password: test
    # 如果使用的jedis 则将lettuce改成jedis即可
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0


logging:
  level:
    com.smallcode.sample.sample.springboot.cache.redis.dao: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
